Repository TheJulge/Frontend, pull requests merged in 2024-04, with the labels that each got.

#8 Feat toast
  .eslintrc.json
  components/commons/toast/Toast.module.scss
  components/commons/toast/Toast.tsx
  next.config.js
  styles/_mixins.scss
  styles/_variables.scss
  styles/globals.css
  tsconfig.json
  utils/constants/toastConstants.ts
Labels: feature

#11 Feat gnb
  components/commons/gnb/Gnb.module.scss
  components/commons/gnb/Gnb.tsx
  components/commons/gnb/GnbSearch.module.scss
  components/commons/gnb/GnbSearch.tsx
  components/commons/gnb/GnbUser.module.scss
  components/commons/gnb/GnbUser.tsx
  global.d.ts
  pages/_document.tsx
  pages/index.tsx
  public/images/logo.svg
  public/images/notification-active.svg
  public/images/notification.svg
  public/images/search.svg
  styles/globals.css
  tsconfig.json
Labels: feature

#10 Feat button
  .eslintrc.json
  components/commons/Button/Button.module.scss
  pages/index.tsx
Labels: feature

#15 fix: develop 브랜치 빌드에러 해결
  .eslintrc.json
  components/commons/gnb/Gnb.tsx
  components/commons/gnb/GnbUser.tsx
  pages/_document.tsx
  pages/index.tsx
Labels: bug

#13 feat: 모달 초기 설정 및 디자인 구현
  components/commons/modal/ChooseModal.tsx
  components/commons/modal/InfoModal.tsx
  components/commons/modal/Modal.module.scss
  components/commons/modal/Portal.tsx
  components/commons/modal/WarnModal.tsx
  components/commons/test
  hooks/test
  hooks/useCloseModal.tsx
  pages/modalTest.tsx
  public/images/ modal/check.svg
  public/images/ modal/info.svg
  public/images/test
  types/global.d.ts
  types/test
  utils/constants/test
  utils/test
Labels: bug, feature

#19 feat: modal 구현 완료
  components/commons/modal/ChooseModal.tsx
  components/commons/modal/InfoModal.tsx
  pages/_document.tsx
  pages/modalTest.tsx
Labels: feature, refactor

#21 feat: 가게 등록 및 공고 공통 인풋 구현
  components/commons/dropDown/Dropdown.module.scss
  components/commons/dropDown/Dropdown.tsx
  components/commons/inputs/basicInput/BasicInput.module.scss
  components/commons/inputs/basicInput/BasicInput.tsx
  components/commons/inputs/moneyInput/MoneyInput.module.scss
  components/commons/inputs/moneyInput/MoneyInput.tsx
  components/commons/inputs/selectInput/SelectInput.module.scss
  components/commons/inputs/selectInput/SelectInput.tsx
  components/commons/inputs/sortSelectInput/SortSelectInput.module.scss
  components/commons/inputs/sortSelectInput/SortSelectInput.tsx
  components/commons/inputs/timeInput/TimeInput.module.scss
  components/commons/inputs/timeInput/TimeInput.tsx
  hooks/useCloseDropDown.tsx
  pages/inputTest.tsx
  public/inputs/dropDownDown.svg
  public/inputs/dropDownUp.svg
  public/inputs/polygonDown.svg
  public/inputs/polygonUp.svg
  tsconfig.json
Labels: feature

#22 feat: 입력값이 숫자인 인풋 숫자만 입력 가능 및 3자리 당 콤마 기능 추가
  components/commons/inputs/moneyInput/MoneyInput.tsx
  components/commons/inputs/timeInput/TimeInput.tsx
  pages/inputTest.tsx
Labels: feature

#26 feat: 로그인 / 회원가입 공통 인풋 구현 및 리펙토링
  components/commons/dropDown/Dropdown.tsx
  components/commons/inputs/basicInput/BasicInput.module.scss
  components/commons/inputs/basicInput/BasicInput.tsx
  components/commons/inputs/moneyInput/MoneyInput.tsx
  components/commons/inputs/selectInput/SelectInput.tsx
  components/commons/inputs/signInput/SignInput.module.scss
  components/commons/inputs/signInput/SignInput.tsx
  components/commons/inputs/sortSelectInput/SortSelectInput.tsx
  components/commons/inputs/timeInput/TimeInput.tsx
  pages/inputTest.tsx
  pages/modalTest.tsx
  utils/constants/signConstants.ts
Labels: feature, refactor

#16 feat: Card 컴포넌트 구현
  components/commons/card/Card.module.scss
  components/commons/card/Card.tsx
  components/commons/card/payIncrease/PayIncrease.module.scss
  components/commons/card/payIncrease/PayIncrease.tsx
  package-lock.json
  package.json
  public/images/card/arrowUpIcon.svg
  public/images/card/clockIcon.svg
  public/images/card/locationIcon.svg
  styles/_mixins.scss
  styles/_variables.scss
  types/noticeTypes.ts
  types/shopTypes.ts
  types/userTypes.ts
  utils/noticeDataFormetters.ts
Labels: bug, feature

#23 feat: filter 구현 완료
  components/commons/Button/Button.module.scss
  components/commons/calendar/Calendar.module.scss
  components/commons/calendar/Calendar.tsx
  components/commons/calendar/CalendarHeader.tsx
  components/commons/filter/Filter.module.scss
  components/commons/filter/Filter.tsx
  components/commons/filter/FilterAmount.module.scss
  components/commons/filter/FilterAmount.tsx
  components/commons/filter/FilterButton.module.scss
  components/commons/filter/FilterButton.tsx
  components/commons/filter/FilterDate.module.scss
  components/commons/filter/FilterDate.tsx
  components/commons/filter/FilterLocation.module.scss
  components/commons/filter/FilterLocation.tsx
  components/commons/filter/FilterTop.module.scss
  components/commons/filter/FilterTop.tsx
  components/commons/gnb/GnbSearch.tsx
  components/commons/gnb/GnbUser.tsx
  components/commons/inputs/moneyInput/MoneyInput.tsx
  global.d.ts
  next.config.js
  package-lock.json
  package.json
  pages/filterTest.tsx
  public/images/close.svg
  public/images/filter/close.svg
  public/images/gnb/notification-active.svg
  public/images/gnb/notification.svg
  public/images/gnb/search.svg
  public/logo
  styles/globals.css
  tsconfig.json
  utils/constants/toastConstants.ts
Labels: feature

#27 error: modal data 구현 완료
  components/commons/modal/ChooseModal.tsx
  components/commons/modal/InfoModal.tsx
  components/commons/modal/Modal.module.scss
  components/commons/modal/Modal.tsx
  components/commons/modal/notification/NotificationContent.module.scss
  components/commons/modal/notification/NotificationContent.tsx
  components/commons/modal/notification/NotificationModal.module.scss
  components/commons/modal/notification/NotificationModal.tsx
  datas/noticeData.ts
  pages/modalTest.tsx
  pages/notiTest.tsx
  public/images/ modal/approve.svg
  public/images/ modal/reject.svg
Labels: bug, feature

#38 Refactor: footer 공통 컴포넌트 구현
  components/commons/footer/Footer.module.scss
  components/commons/footer/Footer.tsx
  pages/test/footerTest.tsx
  public/images/footer/envelope-square.svg
  public/images/footer/facebook-square.svg
  public/images/footer/instagram.svg
Labels: feature

#45 refactor: 카드 컴포넌트 디자인 수정
  components/commons/card/Card.module.scss
  components/commons/card/Card.tsx
  components/commons/card/payIncrease/PayIncrease.module.scss
  components/commons/card/payIncrease/PayIncrease.tsx
  public/images/card/clockIcon.svg
  public/images/card/locationIcon.svg
Labels: refactor

#42 refactor: table컴포넌트 refactoring
  .eslintrc.json
  .idea/shelf/24__4__16___3_37_________Changes_.xml
  .idea/shelf/24__4__16__오후_3_37,_체크아웃_전에_커밋되지_않은_변경_내용_[Changes]/shelved.patch
  .idea/shelf/24__4__16__오후_3_37,_체크아웃_전에_커밋되지_않은_변경_내용_[Changes]1/shelved.patch
  .idea/shelf/24__4__18___4_25_________Changes_.xml
  .idea/shelf/24__4__18___4_25_________Changes_1.xml
  .idea/shelf/24__4__18___4_28_________Changes_.xml
  .idea/shelf/24__4__18__오후_4_25,_체크아웃_전에_커밋되지_않은_변경_내용_[Changes]/shelved.patch
  .idea/shelf/24__4__18__오후_4_25,_체크아웃_전에_커밋되지_않은_변경_내용_[Changes]1/shelved.patch
  .idea/shelf/24__4__18__오후_4_28,_체크아웃_전에_커밋되지_않은_변경_내용_[Changes]/shelved.patch
  .idea/shelf/24__4__18__오후_4_28,_체크아웃_전에_커밋되지_않은_변경_내용_[Changes]1/shelved.patch
  .idea/workspace.xml
  components/commons/pagination/Pagination.module.scss
  components/commons/pagination/Pagination.tsx
  components/table/EmployeeTable.tsx
  components/table/EmployerTable.tsx
  components/table/StatusButton.module.scss
  components/table/Table.module.scss
  components/table/applicationTypes.ts
  components/table/ssr/employee.ssr.ts
  components/table/ssr/employer.ssr.ts
  pages/test/index.tsx
Labels: feature, pr 대기중, refactor

#39 feat: api 정리 및 axios 정의
  libs/alert.ts
  libs/application.ts
  libs/image.ts
  libs/index.ts
  libs/notice.ts
  libs/shop.ts
  libs/test
  libs/user.ts
  package-lock.json
  pages/shops.tsx
  pages/test/filterTest.tsx
  pages/test/inputTest.tsx
  pages/test/modalTest.tsx
  pages/test/notiTest.tsx
  utils/constants/API.ts
Labels: feature

#30 Refactor: tablemodal 구현 완료
  components/commons/modal/tableModal/TableModal.module.scss
  components/commons/modal/tableModal/TableModal.tsx
  components/commons/modal/tableModal/TableModalText.tsx
  components/commons/modal/tableModal/TableModalTop.tsx
  components/table/EmployerTable.tsx
  components/table/applicationTypes.ts
  pages/tableModalTest.tsx
  pages/test/index.tsx
  styles/globals.css
Labels: feature

#47 feat: SignInPage, SignUpPage 기능, Middleware Redirection, axios interceptor 설정, 로그아웃 구현
  components/commons/filter/FilterLocation.tsx
  components/commons/gnb/GnbUser.tsx
  components/commons/gnb/SignOutButton.module.scss
  components/commons/gnb/SignOutButton.tsx
  components/commons/inputs/selectInput/SelectInput.module.scss
  components/commons/inputs/selectInput/SelectInput.tsx
  components/commons/inputs/signInput/SignInput.tsx
  components/commons/inputs/sortSelectInput/SortSelectInput.tsx
  components/sign/SignInForm.module.scss
  components/sign/SignInForm.tsx
  components/sign/SignModal.module.scss
  components/sign/SignModal.tsx
  components/sign/SignUpForm.module.scss
  components/sign/SignUpForm.tsx
  hooks/useSignIn.tsx
  hooks/useSignUp.tsx
  libs/index.ts
  libs/user.ts
  middleware.ts
  package-lock.json
  package.json
  pages/api/cookies.ts
  pages/signin/index.tsx
  pages/signin/signin.module.scss
  pages/signup/index.tsx
  pages/signup/signup.module.scss
  public/images/inputs/dropDownDown.svg
  public/images/inputs/dropDownUp.svg
  public/images/inputs/polygonDown.svg
  public/images/inputs/polygonUp.svg
  public/images/sign/checked.svg
  public/images/sign/mainlogo.svg
  utils/constants/SIGN.ts
  utils/constants/TOAST.ts
Labels: feature

#52 feat : noticeList 페이지 구현
  components/commons/calendar/Calendar.tsx
  components/commons/card/payIncrease/PayIncrease.module.scss
  components/commons/dropDown/Dropdown.module.scss
  components/commons/filter/Filter.module.scss
  components/commons/filter/Filter.tsx
  components/commons/filter/FilterButton.tsx
  components/commons/gnb/GnbUser.tsx
  components/commons/inputs/sortSelectInput/SortSelectInput.module.scss
  components/commons/inputs/sortSelectInput/SortSelectInput.tsx
  components/noticeList/AllNotice.module.scss
  components/noticeList/AllNotice.tsx
  components/noticeList/AllNoticeCard.module.scss
  components/noticeList/AllNoticeCard.tsx
  components/noticeList/CustomizationNotice.module.scss
  components/noticeList/CustomizationNotice.tsx
  components/noticeList/NoticeSort.module.scss
  components/noticeList/NoticeSort.tsx
  components/noticeList/ssr/notice.ssr.ts
  libs/notice.ts
  next.config.js
  package-lock.json
  package.json
  pages/noticeList/index.tsx
  pages/test/inputTest.tsx
  styles/globals.css
  tsconfig.json
  types/noticeTypes.ts
  utils/constants/TOAST.ts
Labels: feature, refactor

#49 feat: 내프로필 디테일 페이지, 내 가게 공고 디테일테이지 구현
  components/commons/modal/TestModal.tsx
  components/commons/pagination/Pagination.module.scss
  components/commons/pagination/Pagination.tsx
  components/profilecard/ProfileCard.module.scss
  components/profilecard/ProfileCard.tsx
  components/shopcard/ShopCard.module.scss
  components/shopcard/ShopCard.tsx
  components/table/EmployeeTable.tsx
  components/table/EmployerTable.tsx
  components/table/applicationTypes.ts
  components/table/emptytable/EmptyTable.module.scss
  components/table/emptytable/EmptyTable.tsx
  components/table/ssr/employee.ssr.ts
  components/table/ssr/employer.ssr.ts
  pages/shops/[id]/notices/[noticeId]/boss/MyNoticeDetailPage.module.scss
  pages/shops/[id]/notices/[noticeId]/boss/index.tsx
  pages/users/[id]/MyPage.module.scss
  pages/users/[id]/index.tsx
  public/images/profilecard/clockIcon.svg
  public/images/profilecard/downarrow.svg
  public/images/profilecard/moreIcon.svg
  public/images/profilecard/phone.svg
  public/images/profilecard/pointer.svg
  ssr/myDetailPageSsr.ts
  ssr/noticeDetailSsr.tsx
  types/noticeTypes.ts
Labels: feature

#56 refactor: 인증 관련 수정사항 반영
  components/commons/modal/completionModal/CompletionModal.module.scss
  components/commons/modal/completionModal/CompletionModal.tsx
  hooks/useSignIn.tsx
  hooks/useSignUp.tsx
  middleware.ts
  pages/api/cookies.ts
  pages/signin/index.tsx
  pages/signup/index.tsx
Labels: refactor

#63 feat: SSR getServerSideProps 에서 Authorization header에 쿠키 삽입, 로그인 쿠키에 isProfile 추가
  components/commons/filter/FilterAmount.tsx
  components/commons/filter/FilterMoneyInput.module.scss
  components/commons/filter/FilterMoneyInput.tsx
  hooks/useSignIn.tsx
  libs/index.ts
  package-lock.json
  utils/findCookieValue.ts
  utils/setServerSideCookie.ts
Labels: feature

#60 feat: 빈페이지 구현, 내프로필상세 페이지 구현
  components/commons/pagination/Pagination.module.scss
  components/commons/pagination/Pagination.tsx
  components/profilecard/ProfileCard.module.scss
  components/profilecard/ProfileCard.tsx
  components/shopcard/ShopCard.module.scss
  components/shopcard/ShopCard.tsx
  components/table/EmployeeTable.tsx
  components/table/EmployerTable.tsx
  components/table/StatusButton.tsx
  components/table/emptytable/EmptyTable.module.scss
  components/table/emptytable/EmptyTable.tsx
  package-lock.json
  pages/shops/[id]/notices/[noticeId]/boss/MyNoticeDetailPage.module.scss
  pages/shops/[id]/notices/[noticeId]/boss/index.tsx
  pages/users/ProfileEmptypage.module.scss
  pages/users/[id]/index.tsx
  pages/users/index.tsx
  ssr/myDetailPageSsr.ts
  ssr/noticeDetailSsr.tsx
  utils/phoneNumberDataFormatter.ts
Labels: feature, pr 대기중

#64 feat: 공고상세 페이지 구현
  components/commons/card/payIncrease/PayIncrease.module.scss
  components/commons/card/payIncrease/PayIncrease.tsx
  components/commons/details/Explanation.module.scss
  components/commons/details/Explanation.tsx
  components/commons/details/NoticeDetailsContainer.module.scss
  components/commons/details/NoticeDetailsContainer.tsx
  components/commons/details/detailCard/NoticeDetailsCard.module.scss
  components/commons/details/detailCard/NoticeDetailsCard.tsx
  components/commons/recent/RecentViewedContainer.module.scss
  components/commons/recent/RecentViewedContainer.tsx
  next.config.js
  package-lock.json
  pages/shops/[id]/notices/[noticeId]/alba/index.tsx
  types/noticeTypes.ts
  utils/getCookieDataFunctions.ts
  utils/noticeDataFormetters.ts
  utils/watchedListFunctions.ts
Labels: bug, feature

#66 feat: noticeList 페이지 구현
  components/commons/card/Card.module.scss
  components/commons/card/Card.tsx
  components/commons/card/payIncrease/PayIncrease.module.scss
  components/commons/filter/Filter.tsx
  components/commons/filter/FilterButton.tsx
  components/commons/filter/FilterLocation.tsx
  components/commons/gnb/GnbSearch.tsx
  components/commons/gnb/GnbUser.module.scss
  components/commons/gnb/GnbUser.tsx
  components/commons/gnb/SignOutButton.tsx
  components/noticeList/AllNotice.module.scss
  components/noticeList/AllNotice.tsx
  components/noticeList/AllNoticeCard.module.scss
  components/noticeList/AllNoticeCard.tsx
  components/noticeList/CustomizationNotice.module.scss
  components/noticeList/CustomizationNotice.tsx
  components/noticeList/NoticeSort.tsx
  components/noticeList/ssr/notice.ssr.ts
  libs/notice.ts
  libs/user.ts
  package-lock.json
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/noticeList/index.tsx
  public/images/404.svg
  styles/404.module.scss
  styles/globals.css
  utils/constants/NOTICE.ts
  utils/constants/TOAST.ts
  utils/getCookie.ts
  utils/noticeDataFormetters.ts
Labels: bug, feature

#74 fix: 카드 링크 오류 해결
  components/commons/gnb/GnbUser.tsx
  components/noticeList/AllNoticeCard.tsx
  components/noticeList/CustomizationNotice.tsx
  libs/user.ts
Labels: bug

#77 fix: gnb 링크 오류 해결
  components/commons/gnb/GnbUser.tsx
Labels: bug

#80 feat: table modal 구현완료
  components/commons/modal/tableModal/TableModal.tsx
  components/profilecard/ProfileCard.module.scss
  components/profilecard/ProfileCard.tsx
  components/table/EmployerTable.tsx
  utils/constants/SELECT.ts
Labels: feature

#81 feat: 가게 정보 상세 페이지 구현
  components/commons/card/Card.tsx
  components/commons/details/NoticeDetailsContainer.tsx
  components/commons/details/detailCard/NoticeDetailsCard.tsx
  components/commons/recent/RecentViewedContainer.tsx
  components/noticeList/AllNoticeCard.tsx
  components/noticeList/CustomizationNotice.tsx
  components/shopcard/shopDetailCard/ShopDetailsCard.module.scss
  components/shopcard/shopDetailCard/ShopDetailsCard.tsx
  components/table/emptytable/EmptyTable.module.scss
  package-lock.json
  package.json
  pages/shops/[id]/ShopDetails.module.scss
  pages/shops/[id]/index.tsx
  pages/shops/[id]/notices/[noticeId]/alba/index.tsx
  types/noticeTypes.ts
  types/shopTypes.ts
Labels: bug, feature, refactor

#91 feat: 공유하기 기능 추가 및 favicon 추가
  components/commons/details/NoticeDetailsContainer.module.scss
  components/commons/details/NoticeDetailsContainer.tsx
  components/share/KaKaoButton.module.scss
  components/share/KaKaoButton.tsx
  components/share/ShareButtons.module.scss
  components/share/ShareButtons.tsx
  components/share/ShareModal.module.scss
  components/share/ShareModal.tsx
  components/share/ShareOpenButton.module.scss
  components/share/ShareOpenButton.tsx
  components/share/UrlShareButton.module.scss
  components/share/UrlShareButton.tsx
  libs/index.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/profile/index.tsx
  pages/shops/[id]/notices/index.tsx
  pages/shops/index.tsx
  pages/signin/index.tsx
  pages/signup/index.tsx
  public/favicon.ico
  public/images/share/Facebook.svg
  public/images/share/Kakao.svg
  public/images/share/Link.svg
  utils/constants/SHARE.ts
Labels: feature

#89 feat: gnb alert 기능 구현 완료
  components/commons/card/Card.module.scss
  components/commons/card/Card.tsx
  components/commons/card/payIncrease/PayIncrease.module.scss
  components/commons/gnb/GnbUser.module.scss
  components/commons/gnb/GnbUser.tsx
  components/commons/modal/notification/NotificationContent.module.scss
  components/commons/modal/notification/NotificationContent.tsx
  components/commons/modal/notification/NotificationModal.module.scss
  components/commons/modal/notification/NotificationModal.tsx
  components/noticeList/CustomizationNotice.tsx
  components/noticeList/ssr/notice.ssr.ts
  libs/alert.ts
  pages/index.tsx
  styles/globals.css
  test.http
  types/alertTypes.ts
Labels: feature

#93 feat: shopUpdatePage post, put 구현
  components/commons/inputs/imageInput/ImageInput.module.scss
  components/commons/inputs/imageInput/ImageInput.tsx
  libs/image.ts
  libs/shop.ts
  pages/shops/index.tsx
  pages/shops/shops.module.scss
Labels: feature

#94 feat: notice page post, put 구현 완료
  components/commons/inputs/moneyInput/MoneyInput.tsx
  components/shopcard/ShopCard.tsx
  libs/notice.ts
  pages/shops/[id]/notices/index.tsx
Labels: feature

#99 chore: readMe 작성
  README.md
  public/readMe/albaNoticeDetail.png
  public/readMe/bossNoticeDetail.png
  public/readMe/calendar.png
  public/readMe/filter.png
  public/readMe/listPage.png
  public/readMe/mNoticeDetailAlba.png
  public/readMe/mNoticeDetailBoss.png
  public/readMe/mlist.png
  public/readMe/mlist2.png
  public/readMe/mlist3.png
  public/readMe/modal1.png
  public/readMe/modal2.png
  public/readMe/msignin.png
  public/readMe/msignup.png
  public/readMe/myShopPage.png
  public/readMe/postShop.png
  public/readMe/profileDetailPage.png
  public/readMe/profilePage.png
  public/readMe/putNotice.png
  public/readMe/putProfilePage.png
  public/readMe/putShop.png
  public/readMe/readmeTitle.png
  public/readMe/search.png
  public/readMe/signInPage.png
  public/readMe/signUpPage.png
Labels: documentation

#98 feat: GitHub login 기능 추가
  components/sign/SignInForm.tsx
  components/sign/SignUpForm.tsx
  components/socialLogin/GithubLogin.module.scss
  components/socialLogin/GithubLogin.tsx
  hooks/useGithubSignUp.tsx
  package-lock.json
  package.json
  pages/api/auth/callback/github.ts
  pages/signin/index.tsx
  pages/signup/index.tsx
  public/images/share/GitHub.svg
  styles/globals.css
Labels: feature

#102 fix: 공고 상세 페이지 수정
  components/commons/card/Card.module.scss
  components/commons/details/Explanation.module.scss
  components/commons/details/Explanation.tsx
  components/commons/details/detailCard/NoticeDetailsCard.module.scss
  components/commons/details/detailCard/NoticeDetailsPay.module.scss
  components/shopcard/ShopCard.module.scss
  components/shopcard/ShopCard.tsx
  components/shopcard/shopDetailCard/ShopDetailsCard.module.scss
  components/shopcard/shopDetailCard/ShopDetailsCard.tsx
  pages/shops/[id]/ShopDetails.module.scss
  pages/shops/[id]/notices/[noticeId]/boss/MyNoticeDetailPage.module.scss
Labels: bug

#103 fix: Build Error 수정
  components/calculater/CalculateModal.tsx
  components/commons/details/detailCard/NoticeDetailsCard.tsx
  components/commons/modal/TestModal.tsx
  components/commons/recent/RecentViewedContainer.tsx
  components/noticeList/CustomizationNotice.tsx
  components/share/KaKaoButton.tsx
  components/table/StatusBadge.tsx
  pages/shops/[id]/notices/[noticeId]/alba/index.tsx
  pages/tableModalTest.tsx
  pages/test/filterTest.tsx
  pages/test/footerTest.tsx
  pages/test/index.tsx
  pages/test/inputTest.tsx
  pages/test/modalTest.tsx
  pages/test/notiTest.tsx
  pages/users/index.tsx
  utils/constants/SHARE.ts
Labels: refactor

#106 fix: 검색 기능 해결
  components/commons/gnb/GnbSearch.tsx
  components/commons/gnb/GnbUser.tsx
Labels: bug
